inherit_from: configs/Tum/tum.yaml
mapping:
  bound: [[-6.,6.0],[-5.0,6.0],[-1.,3.]] 
  marching_cubes_bound: [[-8.,7.5],[-7.5,7.5],[-1.,3.]] 

data:
  datadir: /home/lanyuqing/dataset/TUM/rgbd_dataset_freiburg3_long_office_household
  trainskip: 1
  output: output/TUM/fr_office
  exp_name: test

cam:  
  H: 480 
  W: 640
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 8
  crop_size: [384,512]
  near: 0
  far: 5

