inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,8.2],[-0.3,7.3],[-0.3,2.8]]
  marching_cubes_bound: [[-0.3,8.2],[-0.3,7.3],[-0.3,2.8]]
  clamp: 1.5

data:
  datadir: /home/lanyuqing/dataset/scannet/scene0181_00/frames
  trainskip: 1
  output: output/scannet/scene0181_00
  exp_name: test

grid:
  hash_size: 14

RO:
  sample_range: 3.0

volume:
  weight_clamp: 0.0

cam:
  fx: 575.547668
  fy: 577.459778
  cx: 323.171967
  cy: 236.417465
  near: 0
  far: 8.0
