inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]
  marching_cubes_bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]

data:
  datadir: /home/lanyuqing/dataset/scannet/scene0059_00/frames
  trainskip: 1
  output: output/scannet/scene0059_00
  exp_name: test 

grid:
  hash_size: 12 

RO:
  init_size: 0.09 







