inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[0.0,10.0],[-1.0,9.0],[-1.0,3.0]]
  marching_cubes_bound: [[0.0,10.0],[-1.0,9.0],[-1.0,3.0]]
  clamp: 1.5 

data:
  datadir: /home/lanyuqing/dataset/scannet/scene0169_00/frames
  trainskip: 1
  output: output/scannet/scene0169_00
  exp_name: test

grid:
  hash_size: 16 

RO:
  init_size: 0.09 
  scaling_coefficient: 0.2 
  cut: 0
  sample_range: 3.0

volume:
  x_config:
    len: 6 
  y_config:
    len: 6 

cam:
  fx: 574.540771
  fy: 577.583740
  cx: 322.522827
  cy: 238.558853
  far: 8.0



