inherit_from: configs/Fast_syn/Fast_syn.yaml
mapping:
  bound: [[-3.0,5.0],[-2.0,8.0],[-2.0,2.0]]
  marching_cubes_bound: [[-3.0,5.0],[-2.0,8.0],[-2.0,2.0]]
  
data:
  datadir: /home/lanyuqing/dataset/Fast_syn/apartment_1/frames/
  trainskip: 1
  output: output/Fast_syn/apartment_1
  exp_name: test 

