inherit_from: configs/Fast_syn/Fast_syn.yaml
mapping:
  bound: [[0.0,7.0],[-2.0,2.0],[-2.0,1.5]]
  marching_cubes_bound: [[0.0,7.0],[-2.0,2.0],[-2.0,1.5]]

data:
  datadir: /media/lyq/data/dataset/Fastcamo-synth/FastCaMo-synth-data(raw)/apartment_2/frames/
  trainskip: 1
  output: output/Fast_syn/apartment_2
  exp_name: test 

