inherit_from: configs/Fast_syn/Fast_syn.yaml
mapping:
  bound: [[-6.0,5.0],[-7.0,4.0],[-2.0,2.0]]
  marching_cubes_bound: [[-6.0,5.0],[-7.0,4.0],[-2.0,2.0]]
  
data:
  datadir: /media/lyq/data/dataset/Fastcamo-synth/FastCaMo-synth-data(raw)/office_3/frames/
  trainskip: 1
  output: output/Fast_syn/office3
  exp_name: test 

