inherit_from: configs/Fast_syn/Fast_syn.yaml
mapping:
  bound: [[-4.0,4.0],[-3.5,5.5],[-2.0,2.0]]
  marching_cubes_bound: [[-4.0,4.0],[-3.5,5.5],[-2.0,2.0]]
  
data:
  datadir: /media/lyq/data/dataset/Fastcamo-synth/FastCaMo-synth-data(raw)/office_2/frames/
  trainskip: 1
  output: output/Fast_syn/office2
  exp_name: test
