inherit_from: configs/Fast_syn/Fast_syn.yaml
mapping:
  bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  marching_cubes_bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]

data:
  datadir: /media/lyq/data/dataset/Fastcamo-synth/FastCaMo-synth-data(raw)/room_0/frames/
  trainskip: 1
  output: output/Fast_syn/room0
  exp_name: test
