inherit_from: configs/BS3D/BS3D.yaml
mapping:
  bound: [[37.0,68.0],[-135.0,-100.0],[-13.0,-3.0]]
  marching_cubes_bound: [[37.0,68.0],[-135.0,-100.0],[-13.0,-3.0]]

data:
  datadir: /data/lyq/BS3D/cafeteria
  trainskip: 1
  output: output/BS3D/cafeteria
  exp_name: test




