inherit_from: configs/BS3D/BS3D.yaml
mapping:
  bound: [[-5.0,30.0],[-45.0,-8.0],[-5.0,5.0]]
  marching_cubes_bound: [[-5.0,30.0],[-45.0,-8.0],[-5.0,5.0]]

data:
  datadir: /data/lyq/BS3D/lounge
  trainskip: 1
  output: output/BS3D/lounge 
  exp_name: test 